# 异常

## 1.异常概述与异常体系结构

- 异常：在Java语言中，将程序执行中发生的不正常情况称为“异常” 。 (开发过程中的语法错误和逻辑错误不是异常) 
- Java程序在执行过程中所发生的异常事件可分为两类：
  - Error ：Java虚拟机无法解决的严重问题。如：JVM系统内部错误、资源耗尽等严重情况。比如：StackOverflowError和OOM。一般不编写针对性 的代码进行处理。
  - Exception: 其它因编程错误或偶然的外在因素导致的一般性问题，可以使用针对性的代码进行处理。例如：空指针访问、试图读取不存在的文件、网络连接中断、数组角标越界

### 1.1 常见异常

- NullPointerException  空指针异常
- ArrayIndexOutOfBoundsException  数组角标越界
- NullPointerException  
- ArithmeticException
- ClassCastException  类型转换异常
- NumberFormatException  

## 2.异常处理机制

### 2.1 try-catch-finally

- Java提供的是异常处理的抓抛模型
- Java程序的执行过程中如出现异常，会生成一个**异常类对象**， 该异常对象将被提交给Java运行时系统，这个过程称为抛出 (throw)异常。
- 异常对象的生成:
  - 由虚拟机自动生成：程序运行过程中，虚拟机检测到程序发生了问题，如果在当前代码中没有找到相应的处理程序，就会在后台自动创建一个对应异常类的实例 对象并抛出——自动抛出
  - 由开发人员手动创建：Exception exception = new ClassCastException();——创 建好的异常对象不抛出对程序没有任何影响，和创建一个普通对象一样

#### 2.1.1 原理

异常处理是通过try-catch-finally语句实现的。

try{ ...... //可能产生异常的代码 } 

catch( ExceptionName1 e ){ ...... //当产生ExceptionName1型异常时的处置措施 }

catch( ExceptionName2 e ){ ...... //当产生ExceptionName2型异常时的处置措施 } 

[ finally{ ...... //无论是否发生异常，都**无条件**执行的语句 } ]

- try：捕获异常的第一步是用try{…}语句块选定捕获异常的范围，将可能出现 异常的代码放在try语句块中。
- catch (Exceptiontype e) ：在catch语句块中是对异常对象进行处理的代码。每个try语句块可以伴随 一个或多个catch语句，用于处理可能产生的不同类型的异常对象。如果满足子父类关系，则子类在上面。
- **捕获异常**的有关信息：与其它对象一样，可以访问一个异常对象的成员变量或调用它的方法。
  - getMessage() 获取异常信息，返回字符串
  - printStackTrace() 获取异常类名和异常信息，以及异常出 现在程序中的位置。返回值void。
- finally
  - 捕获异常的最后一步是通过finally语句为异常处理提供一个 统一的出口，使得在控制流转到程序的其它部分以前，能够 对程序的状态作统一的管理。
  - 不论在try代码块中是否发生了异常事件，catch语句是否执 行，catch语句是否有异常，catch语句中是否有return， finally块中的语句都会被执行。
  - finally语句和catch语句是任选的

### 2.2 throws

- 如果一个方法(中的语句执行时)可能生成某种异常，但是并不能确定如何处理这 种异常，则此方法应显示地声明抛出异常，表明该方法将不对这些异常进行处理， 而由该方法的调用者负责处理。

- 在方法声明中用throws语句可以声明抛出异常的列表，throws后面的异常类型可 以是方法中产生的异常类型，也可以是它的父类。

- 声明抛出异常举例：**在方法头部声明抛出，继续向上抛，交给调用者处理**

  public void readFile(String file)  throws FileNotFoundException {

   ……

   // 读文件的操作可能产生FileNotFoundException类型的异常 

  FileInputStream fis = new FileInputStream(file);

   ..…… 

  }

### 2.3 手动抛出异常

- 首先要**生成异常类对象**，然后通过throw语句实现抛出操作(提交给Java运行环境)。 

  throw new RuntimeException(“您输入的数据非法”);

  ---

  IOException e = new IOException();

  throw e;

  ---

  public void regist(int id) throws Exception{

  ​			throw new Exception(“输入数据非法”);

-   可以抛出的异常必须是Throwable或其子类的实例。下面的语句在编译时将会产生语法错误：

  throw new String("want to throw");

### 2.4 用户自定义异常

- 一般地，用户自定义异常类都是RuntimeException的子类。
- 自定义异常类通常需要编写几个重载的构造器。
- 自定义异常需要提供serialVersionUID
- 自定义的异常通过throw抛出。
- 自定义异常最重要的是异常类的名字，当异常出现时，可以根据 名字判断异常类型。
- 用户自定义异常类MyException，用于描述数据取值范围错误信息。用户 自己的异常类必须继承现有的异常类。

#### 2.4.1 例

```java
class MyException extends Exception {
static final long serialVersionUID = 13465653435L;
private int idnumber;
public MyException(String message, int id) {
super(message);
this.idnumber = id;
}
public int getId() {
return idnumber;
}
}

public class MyExpTest {
public void regist(int num) throws MyException {
if (num < 0)
throw new MyException("人数为负值，不合理", 3);
else
System.out.println("登记人数" + num);
}
public void manager() {
try {
regist(100);
} catch (MyException e) {
System.out.print("登记失败，出错种类" + e.getId());
}
System.out.print("本次登记操作结束");
}
public static void main(String args[]) {
MyExpTest t = new MyExpTest();
t.manager();
}
}

```

